### ISSUE TITLE
Wrong 'Editor Theme' is applied when switching to dark mode

### ISSUE THREAD

**Issue by humblebeee** [weisJ/auto-dark-mode#42]
I have this amazing plugin on Android Studio Arctic Fox (2020.3.1) running on Ubuntu 21.04 (GNOME 3.38.5) and only one minor issue, as the title suggests the wrong editor theme is applied after auto-switching to dark mode!

I have selected "Dracula" as my night 'IDE Theme' and a customized color scheme for my 'Editor Theme' but when switching, 'Dracula' is applied as both the IDE and the Editor theme!

**Comment by weisJ** [comment]
Thank you for reporting this issue! Does this only happen with your custom editor theme or with all themes?

**Comment by hummblebee** [comment]
I confirmed and reapplied the settings a few times, actually it's my only option when the wrong theme is applied!

I take back my previous statement, it also happens in new launches not only during sleep. And when I check the plugin settings, the wrong themes are also selected, and I have to select the customized themes again and click Apply.

I'll attach the idea.log, hope it helps. If you need anything else I'd be more than glad to help.
[idea.log](https://github.com/weisJ/auto-dark-mode/files/7317409/idea.log)

**Comment by weisJ** [comment]
Honestly this feels like a rather hackish solution. If there are problems due to timing adding artificial delays will only make the issue more difficult to reproduce. Would you mind sharing the editor scheme you are using?

**Comment by hummblebee** [comment]
Not at all, here you go:
[Color-Schemes.zip](https://github.com/weisJ/auto-dark-mode/files/7352146/Color-Schemes.zip)
The `IntelliJ Light Customized` is used for day time, and the `One Dark Customized` for the night time.

The reason I suggested the above workaround is that I notice a delay like a second or two when changing my IDE themes and it seems like a heavy operation on my machine, I thought maybe this takes a long time and by the time the plugin has changed the the editor theme, our IDE theme just finished applying and hence overriding the editor theme (since IntelliJ always applies the embedded color scheme too for any IDE theme)!

If this is really the case, are there any APIs for changing themes? Like a callback to make sure the IDE theme is completely applied over now, and we can safely proceed to apply the editor color scheme over?

Thank you for your attention!

**Comment by weisJ** [comment]
I made some changes in #43 which should in theory fix the issue you are experiencing. Are you comfortable with building the plugin locally to try it out? If not I can provide a build for you.

**Comment by hummblebee** [comment]
Any progress on this?

I have recorded a screen cast depicting the issue I described earlier (the dark editor theme being broken), I hope it helps.

Thank you again for you time!

https://user-images.githubusercontent.com/18480836/142212865-db1f3548-2828-4bf2-8b1e-483d49184053.mp4

**Comment by weisJ** [comment]
I’m sorry that I couldn’t invest much time into this issue. Other things currently take a lot of my time currently and I didn’t got to spend as much time on my projects as I would like. This is still on my todo list so please be patient. Hopefully I’ll get around to work on this at the weekend :)

**Comment by hummblebee** [comment]
No worries! ;)
Take your time, wish you good luck with whatever has been keeping you busy. :)

**Comment by humblebeee** [comment]
After testing the latest version 1.6.2 on Fedora 36, I can confirm this is fixed but there's another issue with the new `libadwaita` migration on GNOME 42 which I'll create a new issue for that promptly!

Thank you for all the hard work put into this amazing plugin!
