### ISSUE TITLE
Incompatible with IDEA 2021.3

### ISSUE THREAD

**Issue by ivashin** [weisJ/auto-dark-mode#44]
This excellent plugin unfortunately stopped working after updating to IDEA 2021.3 with the following message: "Incompatible: requires IDE build 212.* or earlier"

**Comment by weisJ** [comment]
This is a reoccurring issue with new versions of IDEA. I’ll have to recompile a version which is marked to be compatible with 2021.3. Expect this to take a few days. My plan is to get it done until the weekend :)

**Comment by itsTyrion** [comment]
I successfully recompiled it (on Ubuntu 20; it doesn't compile on Debian?)
 I just don't know how to make the individual jars one plugin :/

**Comment by itsTyrion** [comment]
You should put one disclaimer:
 If the plugin is incompatible, and therefore disabled, theme selection is busted because `autodetect="true"` is still set in `jba_config/laf.xml`. 
For me, this caused the UI to default to Darcula and the editor scheme to IntelliJ light, with the selection box greyed out.
To work around this, I changed it back to false.

**Comment by weisJ** [comment]
> project 'auto-dark-mode' is ambiguous in root project 'auto-dark-mode'. Candidates are: 'auto-dark-mode-base', 'auto-dark-mode-linux', 'auto-dark-mode-linux-gnome', 'auto-dark-mode-macos', 'auto-dark-mode-plugin', 'auto-dark-mode-windows'.

Just `gradlew buildPlugin` should be enough. I'll update the build instructions accordingly.

> You should put one disclaimer:
If the plugin is incompatible, and therefore disabled, theme selection is busted because autodetect="true" is still set in jba_config/laf.xml.
For me, this caused the UI to default to Darcula and the editor scheme to IntelliJ light, with the selection box greyed out.
To work around this, I changed it back to false.

I'm not sure what you are referring to exactly. This plugin doesn't change any settings/configuration in `jba_config/laf.xml.`
Which selection box are you reffering to? The one of this plugin or the default one from IDEA?

**Comment by itsTyrion** [comment]
> This plugin doesn't change any settings/configuration

Weird. It was set to the auto mode that IDEA on Linux doesn't have as yet. I'm referring to the one in IDEA.

**Comment by weisJ** [comment]
Are you also using IDEA on Windows/macOS? This could be an IDEA issue where it tries to apply synced settings which aren’t supported on linux.

**Comment by ivashin** [comment]
Just received an update. Yay!
